{% set name = "WrightTools" %}
{% set version = "2.13.6" %}
{% set sha256 = "4ed81aa8716245d406aa4282703655298132976c6165104978fe205fc917a172" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - h5py
    - matplotlib 2.*
    - numpy
    - python-dateutil
    - pytz
    - scipy

test:
  imports:
    - WrightTools

about:
  home: https://github.com/wright-group/WrightTools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for loading, processing, and plotting multidimensional spectroscopy data.

extra:
  recipe-maintainers:
    - untzag 
