{% set name = "WrightTools" %}
{% set version = "3.0.0" %}
{% set sha256 = "69f4f49ace213016c58a95269f2ff55907167af4b12f6b7f8bf25b6ef3b1d624" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - appdirs
    - h5py >=2.7.0
    - imageio
    - matplotlib 2.*
    - numexpr
    - numpy
    - python-dateutil
    - pytz
    - scipy
    - pytest-runner
    - tidy_headers

test:
  imports:
    - WrightTools

about:
  home: http://wright.tools/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for loading, processing, and plotting multidimensional spectroscopy data.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
