travis:
  secure:
    BINSTAR_TOKEN: rn/QWJdowgB73otmyiTp+jLWCtEOotF8mJg1c2DsXb/FirAc75zbF7DRAqdonT6hD5RpKV9y9C1fPCtL+K2vbQLm3WclvbWvimaBewhJ0Fm+qyQ2eRYsEkJVz6jJKuvowBWQ6vpXKFwuoegRhaBKVVz0H4z5P8nYzmZ6VekqmJAdT2+bRYK77s5AmssrLUZHe2q2ND5B62cii78bxL3Ml5lGgBP+RmNp0LCnMjJX9i70WaFi9v6FRuda5F4U+xxAip8ayCot03ROAJpEpfx71GCXy8YrsBUFTKxjnCaXXjROmXitzCiDXnYmcWjHIgADSt8yT9RMA8l/r20zwUAwbiEZpg2zA7k4q7c9hr/zPEkldPEiW1PGMW9/8WeJeKHF+L9ZSXLZ2MwtV2Vj1gqGrD6+XMT+1/QD0jSXv2zl/wOtzvFrg+6hInjqhGc/8tQBEvacsqKI8mhyb5/5z9NkTlbr9esGkBl2V2NJ27QMa+9A7v/MgnxRtfD816SJ7vP2nWcFiag6CTgF+1Z++U4hQuNqlxR4zUrX86y1JjBgYlbRP4H/ktZP6qwTu7w2y5aQCFeR1s/wFxsdbGvt7RjLtQpMrGJ7tJgagZCW8G9qDGrs7GKcM8pTaSkq70CBYP+BRsgb4SvdMH9JojLhJKR3X37+VOjLxZsSIOaxVZDSzkQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
