travis:
  secure:
    BINSTAR_TOKEN: VeC3niVPMeoMN+ilTHIP972vheMKhpT1X5PLSGgPsASpcN5Kz95wBiF8Xhw4q6YUiL84Dp9q6dF3Q20Eo2nOz7yjP5iIG+EcyChVMiJVfWjuH9ggRYV4Utphs/awlw+jxDxvYnl6Ap6DA30SLqiTAF3+1AtHiwLIo/NIbU9LPkMWbdg0TULATP30KJp/JqDapEoCRDVL+HA7I8KhWHz/JY17XacS+0hxNDPTVw6UvnO0HD49Sd19GwtcQuPt1q0fvpbQsXeodecoKRT8Fe+I726yUeJHpdy0Xg5LOvj8ESMEzYSBcNwUrISbkzNIejWxRiIPl88sYlIZ4ULXzXxcQQMvP4DmSn6j85lATQDLeXKpBRJ/sKi48DDuHrfB/SN64agpC/LQyo5LHsd6f5K30mNyTc1qLGqXRHb8/LN1vOow/hFHJvDb2qUthF9qiypAjuczKXTxYLMVkXOTe6e28AE+HToV70dljFamH08vYLcFAJoGuomJ8E0S1o/CCkBmr4QCwNEWda1RUpE3Hq1u3Kq5/s6siDfILz3IkBn5a5ljNAKyTVxw/wxDicanwdHU0kVcPN5NdlMKcNgGfayWaMLbozOAQxrK9UgJeYPdACLlWg8/rgVapM0XJA3dOtXxxSVOZh+SXjeGWWjNE9j1K+Vvu6KhP6DWh66XsCzs9ZA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
